# Generated by Django 6.0 on 2025-12-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_social", models.CharField(max_length=200)),
                (
                    "profissao",
                    models.CharField(
                        choices=[
                            ("MEDICO", "Médico"),
                            ("PSICOLOGO", "Psicólogo"),
                            ("NUTRICIONISTA", "Nutricionista"),
                        ],
                        max_length=50,
                    ),
                ),
                ("registro_profissional", models.CharField(max_length=50, unique=True)),
                ("cep", models.CharField(max_length=9)),
                ("logradouro", models.CharField(max_length=200)),
                ("numero", models.CharField(max_length=10)),
                ("complemento", models.CharField(blank=True, max_length=100)),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                ("telefone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nome_social"],
                "indexes": [
                    models.Index(fields=["email"], name="professiona_email_a8dc70_idx"),
                    models.Index(
                        fields=["registro_profissional"],
                        name="professiona_registr_8c4b46_idx",
                    ),
                ],
            },
        ),
    ]
