# Generated by Django 6.0 on 2025-12-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField()),
                ("duracao_minutos", models.PositiveIntegerField(default=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGENDADA", "Agendada"),
                            ("CONFIRMADA", "Confirmada"),
                            ("REALIZADA", "Realizada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="AGENDADA",
                        max_length=20,
                    ),
                ),
                ("paciente_nome", models.CharField(max_length=200)),
                ("paciente_email", models.EmailField(max_length=254)),
                ("paciente_telefone", models.CharField(max_length=15)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="professionals.professional",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_hora"],
                "indexes": [
                    models.Index(
                        fields=["professional", "data_hora"],
                        name="appointment_profess_f2b0dd_idx",
                    ),
                    models.Index(
                        fields=["status"], name="appointment_status_8fe9d7_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("duracao_minutos__gte", 15)),
                        name="duracao_minima_15min",
                    )
                ],
            },
        ),
    ]
